<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class BrandsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $brand_names = [
            'ACNE STUDIOS',
            'ACRONYM',
            'Aeta',
            'ALL BLUES',
            'ALLEGE',
            'ANDERSEN ANDERSEN',
            'Anne Thomas',
            'ANNIKA INEZ',
            'ANOTHER FEATHER',
            'ARC’TERYX VEILANCE',
            'ARCH THE',
            'ARIES',
            'ASICS',
            'BAGJACK',
            'BANG＆OLUFSEN',
            'BEAUFILLE',
            'BEAUTIFUL SHOES',
            'BIREKEN STOCK',
            'BLACKMEANS',
            'BOSSERT / SCHORN',
            'BYREDO',
            'CABaN',
            'CAREERING',
            'CHICSTOCKS',
            'CLEANA',
            'CMMN SWDN',
            'CONVERSE Addict',
            'CYDER KEY',
            'DAIRIKU',
            'DELADA',
            'DESCENT ALLTERRAIN',
            'DUST',
            'EASTPACK RAF SIMONS',
            'Edition',
            'Edwina horl',
            'FFIXXED STUDIOS',
            'FilMelange',
            'FOOT THE COACHER',
            'FOOTSTOCK ORIGINALS',
            'FUMITO GANRYU',
            'GREG LAUREN',
            'G-SHOCK',
            'HERNAN HERDEZ',
            'HOLZWELER',
            'HYKE',
            'IENKI IENKI',
            'IRENE',
            'ISABEL MARANT',
            'ISABEL MARANT ETOILE',
            'JANE SMITH',
            'JIL SANDER',
            'Kearny',
            'KIJIMA TAKAYUKI',
            'KIKO KOSTADINOV',
            'KLOKE',
            'KOCHÉ',
            'KWAIDAN EDITIONS',
            'LEWIS LEATHERS',
            'MAISON EUREKA',
            'MAISON MARGIELA',
            'Mame Kurogouchi',
            'MARIA JOBSE',
            'MARIE MAROT',
            'MARTINE ROSE',
            'masu',
            'mister it.',
            'MM6 DEFILE',
            'MM6 MAISON MARGIELA',
            'MONCLER',
            'MONCLER CRAIG GREEN',
            'MONCLER FRAGMENT',
            'MONCLER KITH',
            'MYKITA',
            'MYKITA MAISON MARGIELA',
            'MYKITA MARTIN ROSE',
            'n.i.r.o’s workers',
            'NAPA BY MARTIN ROSE',
            'NIKE',
            'NOVESTA',
            'nunc',
            'OAMC',
            'Off-White',
            'OVERCOAT',
            'Phlannel',
            'PHOTOCOPIEU',
            'Pierre Hardy',
            'PORTVEL',
            'RAF SIMONS',
            'RANDY',
            'RATHEL & WOLF',
            'RE/DONE',
            'REALITY STUDIO',
            'REPRODUCTION OF FOUND',
            'ROA',
            'Rokh',
            'Rototo',
            'SHIGUSA',
            'SIMON MILLER',
            'SOPHIE ANDERSON',
            'SOPHIE BUHAI',
            'SOSHIOTSUKI',
            'STAND',
            'stein',
            'STONE ISLAND',
            'STONE ISLAND SHADOW PROJECTS',
            'sulvam',
            'TAN',
            'TANG TANG',
            'TH',
            'THE BLACK',
            'THE INOUE BROTHERS…',
            'The letters',
            'THE NORTH FACE',
            'THE RERACS',
            'TOGA',
            'TOGA PULLA',
            'TOM WOOD',
            'VISVIM',
            'WE11DONE',
            'WERKSTATT:MUNCHEN',
            'WRIGHT LE CHAPELAIN',
            'Y’S PINK',
            'Y-3',
            'YASHIKI',
            'YUKI HASHIMOTO',
            'z.b.',
        ];

    foreach($brand_names as $brand_name) {
        DB::table('brands')->insert([
            'brand_name' => $brand_name,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);
    }
}
}
